# Generated by Django 4.0 on 2023-10-13 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('community1', 'Assembly'), ('community2', 'Ghana'), ('community3', 'Hope')], default=True, max_length=200)),
            ],
        ),
    ]
