# Generated by Django 4.0 on 2023-10-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydata',
            name='name',
            field=models.CharField(choices=[('community1', 'Assembly'), ('community2', 'Ghana'), ('community3', 'Hope')], default='Community 1', max_length=200),
        ),
    ]
