# Generated by Django 4.0 on 2023-10-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmi', '0002_alter_communitydata_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityData',
        ),
    ]
