# Generated by Django 4.0 on 2023-10-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmi', '0006_community_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='user',
        ),
    ]
