# Generated by Django 4.0 on 2023-10-17 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pmi', '0005_alter_communitydata_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
